"""Generates a PDF verification report summarizing one analysis result."""
import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

DISCLAIMER = (
    "This report is generated by an automated classifier trained on a public "
    "face-swap/GAN dataset. It is a supporting signal for investigation, not "
    "definitive proof of authenticity or manipulation. See project README for "
    "known limitations."
)


def generate_report(analysis: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Synthetic Media Verification Report", styles["Title"]))
    story.append(Paragraph(datetime.now(timezone.utc).strftime("Generated %Y-%m-%d %H:%M UTC"), styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    verdict = analysis.get("verdict", "unknown").upper()
    confidence = analysis.get("confidence") or analysis.get("avg_prob_fake")
    verdict_color = "red" if verdict == "FAKE" else "green"
    story.append(Paragraph(f'Verdict: <font color="{verdict_color}">{verdict}</font>', styles["Heading1"]))
    if confidence is not None:
        story.append(Paragraph(f"Confidence: {confidence * 100:.1f}%", styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    summary_rows = [["Field", "Value"], ["Media type", analysis.get("kind", "-")], ["Filename", analysis.get("filename", "-")]]
    if "suspicious_frame_ratio" in analysis:
        summary_rows.append(["Suspicious frame ratio", f"{analysis['suspicious_frame_ratio'] * 100:.1f}%"])
    if analysis.get("temporal_jitter_score") is not None:
        summary_rows.append(["Temporal jitter score (experimental)", f"{analysis['temporal_jitter_score']:.4f}"])

    table = Table(summary_rows, colWidths=[7 * cm, 8 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.7 * cm))

    for label, key in (("Model attention (Grad-CAM)", "heatmap_png"), ("Frequency spectrum (FFT)", "fft_png"),
                        ("Per-frame score timeline", "timeline_png")):
        img_bytes = analysis.get(key)
        if img_bytes:
            story.append(Paragraph(label, styles["Heading3"]))
            story.append(RLImage(io.BytesIO(img_bytes), width=10 * cm, height=10 * cm, kind="proportional"))
            story.append(Spacer(1, 0.5 * cm))

    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(DISCLAIMER, styles["Italic"]))

    doc.build(story)
    return buffer.getvalue()
